obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0, 0], [1, 0], [1, 1], [0, 1]]
#robot_radius: .5
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /stereo_camera, data_type: PointCloud2, topic: /tegra_stereo/points2, marking: true, clearing: true}

