
obstacle_range: 2.5 
raytrace_range: 3.0 
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

plugins: 
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}

publish_frequency: 1.0

obstacles:
    observation_sources: base_scan
    max_obstacle_height: 50
    track_unknown_space: true
    base_scan: {data_type: PointCloud2 , sensor_frame: /stereo_camera, clearing: true, marking: true, topic: /stereo_camera/points2 , max_obstacle_height: 50 , min_obstacle_height: -50}
