global_costmap:
  resolution: 0.5
  update_frequency: 2
  publish_frequency: 1

  global_frame: map
  static_map: true
  rolling_window: false
  track_unknown_space: false
  inf_is_valid: true
  # max_obstacle_height: 200.0

  height: 80
  width: 80
  origin_x: -40
  origin_y: -40

  plugins:
#    - {name: static_map_lines,          type: "costmap_2d::StaticLayer"}
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
#    - {name: obstacles_laser_global,    type: "costmap_2d::ObstacleLayer"}
