global_costmap:
  global_frame: odom
  rolling_window: true
  track_unknown_space: true
  height: 50
  width: 50
  origin_x: -25
  origin_y: -25
  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
