global_costmap:
  global_frame: map
  static_map: true
  rolling_window: false
  track_unknown_space: false
#  inf_is_valid: true
  height: 50
  width: 50
  origin_x: -25
  origin_y: -25
  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
