global_costmap:
  resolution: 0.5
  update_frequency: 2
  publish_frequency: .5 

  global_frame: costmap
#  static_map: true
  rolling_window: false
  track_unknown_space: false
  inf_is_valid: true
  max_obstacle_height: 200.0

#  height: 150
#  width: 150
#  origin_x: -75
#  origin_y: -75
  plugins:
    - {name: static_map_lines,          type: "costmap_2d::StaticLayer"}
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
#    - {name: obstacles_laser_global,    type: "costmap_2d::ObstacleLayer"}
