local_costmap:
  width: 10 
  height: 5
  global_frame: base_link
  rolling_window: true
  track_unknown_space: false
#  inf_is_valid: true
  height: 6.0
  width: 6.0

  plugins:
    - {name: obstacles,           type: "costmap_2d::ObstacleLayer"}
  #  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
