local_costmap:
  global_frame: base_link
  rolling_window: true
  track_unknown_space: false
  inf_is_valid: true
  resolution: 0.1
  height: 3.0
  width: 3.0
  update_frequency: 10
  publish_frequency: 5


  plugins:
    - {name: obstacles_laser_local,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
