local_costmap:
  width: 10 
  height: 5
  global_frame: base_link
  rolling_window: true

  plugins:
  #  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: obstacles,           type: "costmap_2d::VoxelLayer"}
  #  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
