local_costmap:
  global_frame: base_link
  rolling_window: true
  track_unknown_space: false
#  inf_is_valid: true
  height: 30.0
  width: 30.0

  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
