local_costmap:
  global_frame: base_link
  rolling_window: true

  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  #  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
