local_costmap:
  global_frame: map
  rolling_window: true
  track_unknown_space: false
#  inf_is_valid: true
  height: 6.0
  width: 6.0

  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
