local_costmap:
  global_frame: base_link
  rolling_window: true
  track_unknown_space: true
  inf_is_valid: true
  height: 3.0
  width: 3.0

  plugins:
    - {name: obstacles_laser_local,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
