# Move_base params 
recovery_behaviors: 
  - name: aggressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

# Rate that controller will send command vels
controller_frequency: 5.0

# how long planner will wait in secs before space-clearing operations are performed
planner_patience: 5.0

# how long controller will wait to find a valid control
controller_patience: 15

# rate in hz to run global planning loop. if 0, will only run when a new goal is recevied or when local planner reports plan is blocked
planner_frequency: 2.0

# max times to try before recovery behavior
max_planning_retries: 5

recovery_behaviour_enabled: true

# Global Planner params
GlobalPlanner:
  # if using obstacle layer, must set track_unknown_space to true
  allow_unknown: true 
  
  default_tolerance: 5 
  
  # visualize potential area
  visualize_potential: true  

  # otherwise a*
  use_dijkstra: false
  
  # use quadratic approx for potentials, otherwise use simpler
  use_quadratic: true

  # follow grid boundaries, otherwise gradient descent
  use_grid_path: true

  # use old style navfn behaviors
  old_navfn_behavior: false

EBandPlannerROS:

# Common params
 # Distance tolerance for reaching the goal pose
 xy_goal_tolerance: 0.1 

 # Orientation tolerance for reaching the desired goal pose
 yaw_goal_tolerance: 0.75

 # Angular velocity lower bound that determines if the robot should stop to avoid limit-cycles or locks
 rot_stopped_vel: 0.01

 # Linear velocity lower bound that determines if the robot shoudl stop to avoid limit-cycles or locks
 trans_stopped_vel: 0.01
 
# visualization
 # Lifetime of eband visualization markers 
 marker_lifetime: 0.5 
 
# Elastic Band Params
 # Min distnace that denotes connectivity between consecutive bubbles 
 eband_min_relative_overlap: 0.15

 # Bubble geometric bound regarding tiny bubble distance 
 eband_tiny_bubble_distance: 0.01

 # Bubble geometric bound regarding tiny bubble expansion 
 eband_tiny_bubble_expansion: 0.5

 # Force gain of forces between consecutive bubbles that tend to stretch the elastic band 
 eband_internal_force_gain: 3.0

 # Force gain of forces that tend to move the bubbles away from obstacles 
 eband_external_force_gain: 2.0

 # Number of iterations for eband expansion 
 num_iterations_eband_optimization: 5

 # Number of iterations for reaching the equilibrium between internal and external forces
 eband_equilibrium_approx_max_recursion_depth: 7
 
 # Maximum relative equilibrium overshoot 
 eband_equilibrium_relative_overshoot: 0.5

 # Minimum magnitude of force that is considered significant and used in the calculations 
 eband_significant_force_lower_bound: 0.075
 
 # Costmap weight factor used in calculation of distance to obstacles 
 costmap_weight: 10.0
 
 # Trajectory Controller Parameters 
 # Maximum linear velocity
 max_vel_lin: 1.5
 
 # Maximum angular velocity 
 max_vel_th: 1
 
 # Minimum linear velocity 
 min_vel_lin: 0
 
 # Minimum angular velocity 
 min_vel_th: 0

 # Minimum in-place angular velocity 
 min_in_place_vel_th: 1.0

 # Minimum in-place linear velocity 
 in_place_trans_vel: 0

 # Proportional gain of the PID ontroller 
 k_prop: 1.5

 # Damping gain of the PID controller 
 k_damp: 2.5
 
 # Control rate 
 Ctrl_Rate: 10.0

 # Maximum allowable acceleration 
 max_acceleration: 4

 # Virtual mass 
 virtual_mass: 0.75

 # Maximum linear acceleration 
 max_translational_acceleration: 5

 # Maximum angular acceleration 
 max_rotational_acceleration: 5

 # Rotation correction threshold 
 rotation_correction_threshold: 0.6

 # Denotes whether or not to use diff drive mode 
 differential_drive: True

 # Multiplier of a
 bubble_velocity_multiplier: 2.0

 # Multiplier of rotation threshold 
 rotation_threhsold_multiplier: 6

 # Determines whether to try getting closer to the goal, in case of going past the tolerance 
 disallow_hysteresis: False
