controller_frequency: 5.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner
TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 10
  acc_lim_theta: 10

  max_vel_x: 5 
  min_vel_x: 0.0

  max_vel_theta: 3
  min_vel_theta: 1
  min_in_place_vel_theta: 5 

  holonomic_robot: true
  escape_vel: -0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 20.0

  # Trajectory scoring parameters
  meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
  occdist_scale:  0.1 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  pdist_scale: 0.75  #     The weighting for how much the controller should stay close to the path it was given . default 0.6
  gdist_scale: 1.0 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

  heading_lookahead: 0.325  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  heading_scoring_timestep: 0.8   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
  dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
  simple_attractor: false
  publish_cost_grid_pc: true  

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1


EBandPlannerROS:

# Common params
 # Distance tolerance for reaching the goal pose
 xy_goal_tolerance: 0.1 

 # Orientation tolerance for reaching the desired goal pose
 yaw_goal_tolerance: 0.75

 # Angular velocity lower bound that determines if the robot should stop to avoid limit-cycles or locks
 rot_stopped_vel: 0.01

 # Linear velocity lower bound that determines if the robot shoudl stop to avoid limit-cycles or locks
 trans_stopped_vel: 0.01
 
# visualization
 # Lifetime of eband visualization markers 
 marker_lifetime: 0.5 
 
# Elastic Band Params
 # Min distnace that denotes connectivity between consecutive bubbles 
 eband_min_relative_overlap: 0.15

 # Bubble geometric bound regarding tiny bubble distance 
 eband_tiny_bubble_distance: 0.01

 # Bubble geometric bound regarding tiny bubble expansion 
 eband_tiny_bubble_expansion: 0.5

 # Force gain of forces between consecutive bubbles that tend to stretch the elastic band 
 eband_internal_force_gain: 3.0

 # Force gain of forces that tend to move the bubbles away from obstacles 
 eband_external_force_gain: 2.0

 # Number of iterations for eband expansion 
 num_iterations_eband_optimization: 5

 # Number of iterations for reaching the equilibrium between internal and external forces
 eband_equilibrium_approx_max_recursion_depth: 7
 
 # Maximum relative equilibrium overshoot 
 eband_equilibrium_relative_overshoot: 0.5

 # Minimum magnitude of force that is considered significant and used in the calculations 
 eband_significant_force_lower_bound: 0.075
 
 # Costmap weight factor used in calculation of distance to obstacles 
 costmap_weight: 10.0
 
 # Trajectory Controller Parameters 
 # Maximum linear velocity
 max_vel_lin: 1.5
 
 # Maximum angular velocity 
 max_vel_th: 1
 
 # Minimum linear velocity 
 min_vel_lin: 0.3
 
 # Minimum angular velocity 
 min_vel_th: 0

 # Minimum in-place angular velocity 
 min_in_place_vel_th: 1.0

 # Minimum in-place linear velocity 
 in_place_trans_vel: 0.1

 # Proportional gain of the PID ontroller 
 k_prop: 1.5

 # Damping gain of the PID controller 
 k_damp: 2.5
 
 # Control rate 
 Ctrl_Rate: 10.0

 # Maximum allowable acceleration 
 max_acceleration: 4

 # Virtual mass 
 virtual_mass: 0.75

 # Maximum linear acceleration 
 max_translational_acceleration: 5

 # Maximum angular acceleration 
 max_rotational_acceleration: 5

 # Rotation correction threshold 
 rotation_correction_threshold: 0.7

 # Denotes whether or not to use diff drive mode 
 differential_drive: True

 # Multiplier of a
 bubble_velocity_multiplier: 2.0

 # Multiplier of rotation threshold 
 rotation_threhsold_multiplier: 3

 # Determines whether to try getting closer to the goal, in case of going past the tolerance 
 disallow_hysteresis: False
