footprint: [[-0.375, -0.225],  [0.375, -0.225],[0.375, 0.225],[-0.375, 0.225]]
footprint_padding: 0.1
always_send_full_costmap: true


update_frequency: 10.0
publish_frequency: 5.0
robot_base_frame: base_link
#static_map: false
#rolling_window: true  
inf_is_valid: true

resolution: 0.1 
transform_tolerance: 0.2

#static_map:
#  map_topic: /map
#  subscribe_to_updates: true
#  enabled: true
#  height: 50
#  width: 50
#  origin_x: -25
#  origin_y: -25

#static_map_lines:
#  map_topic: /map_lines
#  subscribe_to_updates: true
#  enabled: true
#  trinary_costmap: false
#  height: 50
#  width: 50
#  origin_x: -25
#  origin_y: -25



obstacles_laser:
  obstacle_range: 5
  raytrace_range: 10
  enabled: true
  observation_sources: base_scan
  base_scan: {
      sensor_frame: /stereo_camera,
#      data_type: PointCloud2, 
      data_type: LaserScan, 
      topic: /test/scan, 
      marking: true, 
      clearing: true,
      inf_is_valid: true
  }

inflation:
    inflation_radius: 3
