#footprint: [[-0.27, -0.3],  [0.93, -0.3],[0.93, 0.3],[-0.27, 0.3]]
footprint: [[-0.2, -0.01],  [-0.19, -0.01],[-0.19, 0.01],[-0.2, 0.01]]
footprint_padding: 0.5
always_send_full_costmap: false


robot_base_frame: base_link
#static_map: false
#rolling_window: true  
inf_is_valid: true

transform_tolerance: 2

#static_map:
#  map_topic: /map
#  subscribe_to_updates: true
#  enabled: true
#  height: 50
#  width: 50
#  origin_x: -25
# origin_y: -25

static_map_lines:
  map_topic: /map_lines
  subscribe_to_updates: true
  enabled: true
  trinary_costmap: false
#  height: 50
#  width: 50
#  origin_x: -25
#  origin_y: -25



obstacles_laser_local:
  obstacle_range: 3 
  raytrace_range: 4 
  enabled: true
  observation_sources: full_scan angle_filtered_scan
  full_scan: {
      max_obstacle_height: 20000.0,
      min_obstacle_height: -1,
      sensor_frame: /laser,
      data_type: LaserScan, 
      topic: /scan,
      clearing: true,
      marking:  false,
      inf_is_valid: true
  }
  angle_filtered_scan: {
      max_obstacle_height: 20000.0,
      min_obstacle_height: -1,
      sensor_frame: /laser,
      data_type: LaserScan, 
      topic: /scan_filtered,
      marking:  true,
      clearing: true,
      inf_is_valid: true
  }

obstacles_laser_global:
  obstacle_range: 3 
  raytrace_range: 4 
  enabled: true
  observation_sources: full_scan angle_filtered_scan
  full_scan: {
      max_obstacle_height: 20000.0,
      min_obstacle_height: -1,
      sensor_frame: /laser,
      data_type: LaserScan, 
      topic: /scan,
      clearing: true,
      marking:  true,
      inf_is_valid: true
  }
obstacles_laser:
  obstacle_range: 3 
  raytrace_range: 4 
  enabled: true
  observation_sources: full_scan
  full_scan: {
      max_obstacle_height: 20000.0,
      min_obstacle_height: -1,
      sensor_frame: /laser,
      data_type: LaserScan, 
      topic: /scan,
      clearing: true,
      marking:  true,
      inf_is_valid: true
  }

inflation:
    inflation_radius: 1.0
    cost_scaling_factor: 1.0 
