obstacle_range: 8
raytrace_range: 10
footprint: [[-0.375, -0.225],  [0.375, -0.225],[0.375, 0.225],[-0.375, 0.225]]
footprint_padding: 0.01
always_send_full_costmap: true



update_frequency: 2.0
publish_frequency: 2.0
robot_base_frame: /base_link
static_map: false
rolling_window: true  

resolution: 0.1 
transform_tolerance: 0.2


static:
    map_topic: /map
    subscribe_to_updates: true


obstacles:
  observation_sources: stereo_mark 
  stereo_mark: {
      sensor_frame: /gps,
      data_type: LaserScan, 
      #min_obstacle_height: 0.0,
      #max_obstacle_height: 1.0,
      topic: /scan, 
      marking: true, 
      clearing: true,
      #mark_threshold: 2,
      inf_is_valid: true
  }
  #z_resolution: 0.2
  #z_height: 100
  #publish_voxel_map: true


  #stereo_clear: {
      #sensor_frame: /stereo_camera,
      #data_type: LaserScan, 
      #min_obstacle_height: -10.0,
      #max_obstacle_height: 10.0,
      #topic: /scan, 
      #marking: false, 
      #clearing: true,
      ##unknown_threshold: 1,
      #inf_is_valid: true
  #}
  


inflation:
    inflation_radius: 1.0
