obstacle_range: 8
raytrace_range: 10
footprint: [[-0.375, -0.225],  [0.375, -0.225],[0.375, 0.225],[-0.375, 0.225]]
footprint_padding: 0.01
always_send_full_costmap: true



update_frequency: 2.0
publish_frequency: 2.0
robot_base_frame: /base_link
static_map: false
rolling_window: true  

resolution: 0.1 
transform_tolerance: 0.2


static:
    map_topic: /map
    subscribe_to_updates: true


obstacles:
  observation_sources: stereo_mark 
  stereo_mark: {
      sensor_frame: /gps,
      data_type: LaserScan, 
      topic: /scan, 
      marking: true, 
      clearing: true,
      inf_is_valid: true
  }

inflation:
    inflation_radius: 1.0
