footprint: [[-0.27, -0.3],  [0.93, -0.3],[0.93, 0.3],[-0.27, 0.3]]
footprint_padding: 0.5
always_send_full_costmap: true


update_frequency: 10.0
publish_frequency: 5.0
robot_base_frame: base_link
#static_map: false
#rolling_window: true  
inf_is_valid: true

resolution: 0.1 
transform_tolerance: 0.2

#static_map:
#  map_topic: /map
#  subscribe_to_updates: true
#  enabled: true
#  height: 50
#  width: 50
#  origin_x: -25
#  origin_y: -25

static_map_lines:
  map_topic: /map_lines
  subscribe_to_updates: true
  enabled: true
  trinary_costmap: false
#  height: 50
#  width: 50
#  origin_x: -25
#  origin_y: -25



obstacles_laser_local:
  obstacle_range: 3 
  raytrace_range: 4 
  enabled: true
  observation_sources: full_scan angle_filtered_scan
  full_scan: {
      sensor_frame: /laser,
      data_type: LaserScan, 
      topic: /scan,
      clearing: true,
      marking:  false,
      inf_is_valid: true
  }
  angle_filtered_scan: {
      sensor_frame: /laser,
      data_type: LaserScan, 
      topic: /scan_filtered,
      marking:  true,
      clearing: true,
      inf_is_valid: true
  }

obstacles_laser_global:
  obstacle_range: 3 
  raytrace_range: 4 
  enabled: true
  observation_sources: full_scan angle_filtered_scan
  full_scan: {
      sensor_frame: /laser,
      data_type: LaserScan, 
      topic: /scan,
      clearing: true,
      marking:  true,
      inf_is_valid: true
  }


inflation:
    inflation_radius: .75
